version: "3.9"

services:
  postgres:
    image: postgres:16 
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: my_app
    ports:
      - "8000:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: link_shortening_service
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - postgres
      - redis

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data: